version: '3.1'

services:
  redis:
    container_name: redis
    image: redis:6.2.4
    ports:
      - 6379:6379
    volumes:
      - ../volumes/data:/data
      - ../volumes/input:/input
    entrypoint: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  data:
