version: '3.1'

services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ../volumes/data:/data/db
      - ../volumes/input:/input/

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    depends_on: mongo
    ports:
      - 8081:8081

volumes:
  data:
